@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Wed Apr 17 16:12:06 +0100 2024
=======
REM Generated by Vivado on Wed Apr 17 12:31:00 +0100 2024
>>>>>>> 9a96bf9107f583be666d3047a411be3dee62d96b
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_cmdProc_interim_behav -key {Behavioral:sim_1:Functional:tb_cmdProc_interim} -tclbatch tb_cmdProc_interim.tcl -view C:/Users/talli/OneDrive/Documents/EEE_Year_2/Digital Design/Assignment2/Assignment2_Git/CommandProcessor/cmdProc_behav.wcfg -log simulate.log"
call xsim  tb_cmdProc_interim_behav -key {Behavioral:sim_1:Functional:tb_cmdProc_interim} -tclbatch tb_cmdProc_interim.tcl -view C:/Users/talli/OneDrive/Documents/EEE_Year_2/Digital Design/Assignment2/Assignment2_Git/CommandProcessor/cmdProc_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
